name: Next.js CI/CD Pipeline for AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install
          # Ensure radix-ui themes package is installed if not in package.json
          npm install @radix-ui/themes

      - name: Check for globals.css file
        run: |
          echo "Verifying if globals.css exists..."
          ls -la ./src/styles/globals.css || echo "globals.css not found, please check the file path."

      - name: Build Next.js App
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key for Lightsail (Application Instance)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/git_hub
          chmod 600 ~/.ssh/git_hub
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_APP_IP }} >> ~/.ssh/known_hosts

      - name: Verify Next.js build output
        run: |
          echo "Verifying the Next.js build output..."
          ls -la .next

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .next/

      - name: Deploy Next.js App to AWS Lightsail
        env:
          LIGHTSAIL_APP_IP: ${{ secrets.LIGHTSAIL_APP_IP }}
        run: |
          echo "Starting deployment to AWS Lightsail..."

          # Ensure the target directory exists with proper permissions
          ssh -i ~/.ssh/git_hub ubuntu@$LIGHTSAIL_APP_IP "
            sudo mkdir -p /var/www/html/nextjs &&
            sudo chown -R ubuntu:ubuntu /var/www/html/nextjs
          "

          # Sync build files and package.json to Lightsail
          rsync -avzO --no-perms --delete --exclude='.git' --exclude='node_modules' --exclude='*.log' \
            -e "ssh -i ~/.ssh/git_hub" . \
            ubuntu@$LIGHTSAIL_APP_IP:/var/www/html/nextjs

          # SSH into Lightsail instance to install dependencies and run the app
          ssh -i ~/.ssh/git_hub ubuntu@$LIGHTSAIL_APP_IP "
            cd /var/www/html/nextjs &&
            npm install --production &&
            pm2 restart next-app || pm2 start npm --name 'next-app' -- start
          "
