name: CI/CD Pipeline for Next.js to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key for Lightsail
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/lightsail_key
          chmod 600 ~/.ssh/lightsail_key

      - name: Deploy Next.js Application to AWS Lightsail
        env:
          LIGHTSAIL_IP: "13.43.41.67"
        run: |
          echo "Deploying Next.js application to AWS Lightsail..."

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key ubuntu@$LIGHTSAIL_IP "
            sudo mkdir -p /var/www/html
            sudo chown -R ubuntu:ubuntu /var/www/html
          "

          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next/cache' \
            -e 'ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key' \
            ./ ubuntu@$LIGHTSAIL_IP:/var/www/html

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key ubuntu@$LIGHTSAIL_IP "
            echo 'Setting up app on Lightsail...'

            sudo apt update

            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            if ! command -v npm &> /dev/null; then
              sudo apt install -y npm
            fi

            cd /var/www/html

            echo 'Installing npm dependencies...'
            npm ci

            REQUIRED_PACKAGES=(currency.js html2canvas-pro jspdf)
            for pkg in \"\${REQUIRED_PACKAGES[@]}\"; do
              if ! npm ls \$pkg > /dev/null 2>&1; then
                echo \"ERROR: Missing required package: \$pkg\"
                exit 1
              fi
            done

            echo 'Building application...'
            npm run build

            if ! command -v pm2 &> /dev/null; then
              sudo npm install pm2@latest -g
            fi

            pm2 delete nextjs-app || true
            pm2 start npm --name 'nextjs-app' -- start -- -p 4000
            pm2 save

            if systemctl is-active --quiet nginx; then
              sudo systemctl reload nginx
            fi
          "

      - name: Cleanup
        run: rm -f ~/.ssh/lightsail_key
